In [1]:
import pandas as pd
import numpy as np

from scipy.stats import (
    ttest_ind,
    f_oneway,
    chi2_contingency,
    shapiro,
    levene,
    mannwhitneyu
)

import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
sales_df = pd.read_csv(
    "../Dataset/clean_retail.csv"
)

In [3]:
sales_df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Revenue,Year,Month,Day
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,83.4,2009,12,1
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0,2009,12,1
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0,2009,12,1
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,100.8,2009,12,1
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,30.0,2009,12,1

In [4]:
sample_revenue = (
    sales_df["Revenue"]
    .sample(
        5000,
        random_state=42
    )
)

In [5]:
stat, p = shapiro(
    sample_revenue
)

print("Statistic:", stat)
print("P-value:", p)

Statistic: 0.23995639692472004
P-value: 1.8255016807014754e-89

In [6]:
uk = sales_df[
    sales_df["Country"]=="United Kingdom"
]["Revenue"]

germany = sales_df[
    sales_df["Country"]=="Germany"
]["Revenue"]

stat,p = levene(
    uk,
    germany
)

print("Statistic:", stat)
print("P-value:", p)

Statistic: 1.1998935692956703
P-value: 0.27334331943303486

In [7]:
uk = sales_df[
    sales_df["Country"]
    == "United Kingdom"
]["Revenue"]

germany = sales_df[
    sales_df["Country"]
    == "Germany"
]["Revenue"]

stat, p = ttest_ind(
    uk,
    germany,
    equal_var=False
)

print("Statistic:", stat)
print("P-value:", p)

Statistic: -13.518005725318826
P-value: 1.3819168757838266e-41

In [8]:
print("UK Mean:",
      uk.mean())

print("Germany Mean:",
      germany.mean())

UK Mean: 20.544662268628244
Germany Mean: 25.865367027750732

In [9]:
countries = [
    "United Kingdom",
    "Germany",
    "France"
]

In [10]:
uk = sales_df[
    sales_df["Country"]=="United Kingdom"
]["Revenue"]

germany = sales_df[
    sales_df["Country"]=="Germany"
]["Revenue"]

france = sales_df[
    sales_df["Country"]=="France"
]["Revenue"]

In [11]:
from scipy.stats import f_oneway

stat, p = f_oneway(
    uk,
    germany,
    france
)

print("Statistic:", stat)
print("P-value:", p)

Statistic: 7.4158095637637205
P-value: 0.0006017104165308536

In [12]:
table = pd.crosstab(
    sales_df["Country"],
    sales_df["Month"]
)

table.head()

Month       1    2    3    4    5    6    7    8    9    10   11   12
Country
Australia  127  121  127   35  175  279  177  114  123  255  211   45
Austria      0   77   54   62   85   18   55  150   96   86  186   53
Bahrain      0    0    0    0   39    0    0    0    0   20    0    0
Belgium    150  180  207  231  153  365  232  272  250  342  464  209
Brazil       0    0    0   32    0    0    0    0   62    0    0    0

In [13]:
from scipy.stats import chi2_contingency

stat, p, dof, expected = chi2_contingency(
    table
)

print("Statistic:", stat)
print("P-value:", p)
print("Degrees of Freedom:", dof)

Statistic: 22755.049110697088
P-value: 0.0
Degrees of Freedom: 440

In [14]:
stat, p = mannwhitneyu(
    uk,
    germany
)

print("Statistic:", stat)
print("P-value:", p)

Statistic: 3543237526.0
P-value: 0.0