In [11]:
query = """
SELECT COUNT(*)
AS total_transactions
FROM retail_sales
"""

pd.read_sql(
    query,
    conn
)

   total_transactions
0              779425

In [12]:
query = """
SELECT COUNT(*)
AS total_transactions
FROM retail_sales
"""

pd.read_sql(
    query,
    conn
)

   total_transactions
0              779425

In [13]:
import os

print(os.getcwd())

c:\Users\varun\OneDrive\Desktop\Projects\Retail_Analytics_Project\Python

In [14]:
import sqlite3

conn = sqlite3.connect(
    "../retail.db"
)

query = """
SELECT name
FROM sqlite_master
WHERE type='table';
"""

import pandas as pd

pd.read_sql(
    query,
    conn
)

           name
0  retail_sales

In [15]:
import pandas as pd
import sqlite3

sales_df = pd.read_csv(
    "../Dataset/clean_retail.csv"
)

conn = sqlite3.connect(
    "../retail.db"
)

sales_df.to_sql(
    "retail_sales",
    conn,
    if_exists="replace",
    index=False
)

print("Table Created Successfully")

Table Created Successfully

In [2]:
print("Table Created Successfully")

Table Created Successfully

In [16]:
query = """
SELECT COUNT(*)
AS total_transactions
FROM retail_sales
"""

pd.read_sql(
    query,
    conn
)

   total_transactions
0              779425

In [17]:
query = """
SELECT
SUM(Revenue)
AS total_revenue
FROM retail_sales
"""

pd.read_sql(
    query,
    conn
)

   total_revenue
0   1.737480e+07

In [5]:
query = """
SELECT
SUM(Revenue)
AS total_revenue
FROM retail_sales
"""

pd.read_sql(query, conn)

   total_revenue
0   1.737480e+07

In [6]:
query = """
SELECT
SUM(Revenue)
AS total_revenue
FROM retail_sales
"""

pd.read_sql(
    query,
    conn
)

   total_revenue
0   1.737480e+07

In [18]:
query = """
SELECT
COUNT(
DISTINCT "Customer ID"
)
AS unique_customers
FROM retail_sales
"""

pd.read_sql(
    query,
    conn
)

   unique_customers
0              5878

In [19]:
query = """
SELECT

Description,

SUM(
Revenue
)
AS revenue

FROM retail_sales

GROUP BY Description

ORDER BY revenue DESC

LIMIT 10
"""

pd.read_sql(
    query,
    conn
)

                          Description    revenue
0            REGENCY CAKESTAND 3 TIER  277656.25
1  WHITE HANGING HEART T-LIGHT HOLDER  247048.01
2         PAPER CRAFT , LITTLE BIRDIE  168469.60
3                              Manual  151777.67
4             JUMBO BAG RED RETROSPOT  134307.44
5                             POSTAGE  124648.04
6       ASSORTED COLOUR BIRD ORNAMENT  124351.86
7                       PARTY BUNTING  103283.38
8      MEDIUM CERAMIC TOP STORAGE JAR   81416.73
9     PAPER CHAIN KIT 50'S CHRISTMAS    76598.18

In [9]:
query = """
SELECT
"Customer ID",
SUM(Revenue) AS revenue
FROM retail_sales
GROUP BY "Customer ID"
ORDER BY revenue DESC
LIMIT 10
"""

pd.read_sql(
    query,
    conn
)

   Customer ID    revenue
0      18102.0  580987.04
1      14646.0  528602.52
2      14156.0  313437.62
3      14911.0  291420.81
4      17450.0  244784.25
5      13694.0  195640.69
6      17511.0  172132.87
7      16446.0  168472.50
8      16684.0  147142.77
9      12415.0  144458.37

In [10]:
query = """
SELECT
Country,
SUM(Revenue) AS revenue
FROM retail_sales
GROUP BY Country
ORDER BY revenue DESC
"""

pd.read_sql(
    query,
    conn
)

                 Country       revenue
0         United Kingdom  1.438923e+07
1                   EIRE  6.165705e+05
2            Netherlands  5.540381e+05
3                Germany  4.250197e+05
4                 France  3.487690e+05
5              Australia  1.692835e+05
6                  Spain  1.083325e+05
7            Switzerland  1.000619e+05
8                 Sweden  9.151582e+04
9                Denmark  6.858069e+04
10               Belgium  6.538782e+04
11                Norway  5.632250e+04
12              Portugal  5.555478e+04
13       Channel Islands  4.462333e+04
14                 Japan  4.302391e+04
15                 Italy  3.210817e+04
16               Finland  2.992554e+04
17             Singapore  2.531706e+04
18                Cyprus  2.484995e+04
19               Austria  2.361301e+04
20                Greece  1.909619e+04
21                Poland  1.065429e+04
22                Israel  1.041524e+04
23  United Arab Emirates  9.202690e+03
24           Unspecified  8.607350e+03
25                   USA  8.366860e+03
26                 Malta  8.099090e+03
27               Iceland  4.921530e+03
28             Lithuania  4.892680e+03
29                Canada  4.883040e+03
30              Thailand  3.070540e+03
31                   RSA  1.933740e+03
32               Lebanon  1.693880e+03
33                Brazil  1.411870e+03
34               Bahrain  1.354370e+03
35    European Community  1.300250e+03
36                 Korea  1.118510e+03
37        Czech Republic  8.267400e+02
38           West Indies  5.364100e+02
39          Saudi Arabia  1.459200e+02
40               Nigeria  1.403900e+02

In [20]:
query = """
SELECT
Year,
Month,
SUM(Revenue) AS revenue
FROM retail_sales
GROUP BY Year, Month
ORDER BY Year, Month
"""

pd.read_sql(
    query,
    conn
)

    Year  Month      revenue
0   2009     12   683504.010
1   2010      1   555802.672
2   2010      2   504558.956
3   2010      3   696978.471
4   2010      4   591982.002
5   2010      5   597833.380
6   2010      6   636371.130
7   2010      7   589736.170
8   2010      8   602224.600
9   2010      9   829013.951
10  2010     10  1033112.010
11  2010     11  1166460.022
12  2010     12   570422.730
13  2011      1   568101.310
14  2011      2   446084.920
15  2011      3   594081.760
16  2011      4   468374.331
17  2011      5   677355.150
18  2011      6   660046.050
19  2011      7   598962.901
20  2011      8   644051.040
21  2011      9   950690.202
22  2011     10  1035642.450
23  2011     11  1156205.610
24  2011     12   517208.440